# Site settings
title: "Lingyun Hao's Homepage"
description: "Homepage for Lingyun Hao"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Lingyun Hao"
resume_title:                   "Master of ECE at Carnegie Mellon University"

# used for header info
resume_header_contact_info:     "(713) 382-6523 • lingyunh@andrew.cmu.edu"
display_header_contact_info:    "true"
resume_header_intro: "<p>I am a master student majoring in Electrical & Computer Engineering (ECE) at Carnegie Mellon University. Prior to my graduate study, I obtained a bachelor degree in Electronic and Information Engineering at Xidian University (China) with a cumulative GPA of 3.75/4.0, and stuided at Rice University as a master of ECE for a semester. I will start my SDE internship shortly at Amazon this summer, and I am open to full-time positions starting from summer 2020.</p>"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/lingyunhao/lingyunhao.github.io"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/lingyunhao/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "https://lingyunhao.github.io/"
  # resume_medium_url:            "https://medium.com/@jglovier"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
